---
AWSTemplateFormatVersion: "2010-09-09"

Transform: AWS::Serverless-2016-10-31

Description: Route apex domain to subdomain

Parameters:
  ProjectName:
    Description: Name for this project
    Type: String
    Default: iamjkahn.com hosting

  SiteDomain:
    Description: Site url
    Type: String
    Default: iamjkahn.com

  HostedZoneId:
    Description: ID for the domain hosted zone in Route 53
    Type: String

  RedirectUrl:
    Description: Site url
    Type: String
    Default: https://blog.iamjkahn.com

Resources:
  ApexBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref SiteDomain
      # AccessControl: PublicRead
      # OwnershipControls:
      #   Rules:
      #     - ObjectOwnership: ObjectWriter
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref RedirectUrl
          Protocol: https
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        # Aliases:
        #   - !Ref SiteDomain
        ViewerCertificate:
          AcmCertificateArn: !Ref DomainCertificate
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
        Enabled: true
        DefaultCacheBehavior:
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          TargetOriginId: "apex-bucket-origin"
          ViewerProtocolPolicy: redirect-to-https
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt RedirectFunction.FunctionARN
        Origins:
          - Id: "apex-bucket-origin"
            DomainName: !GetAtt ApexBucket.DomainName
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
  
  DomainCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref SiteDomain
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref SiteDomain
          HostedZoneId: !Ref HostedZoneId
  
  RedirectFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: RedirectFunction
      AutoPublish: true
      FunctionConfig:
        Comment: !Sub "Redirect to ${RedirectUrl}"
        Runtime: cloudfront-js-2.0
      FunctionCode: !Sub |
        function handler(event) {
          var request = event.request;
          var headers = request.headers;
          var apexDomain = "${SiteDomain}";
          var redirectTo = "${RedirectUrl}";

          if (headers.host && headers.host.value === apexDomain) {
            return {
              statusCode: 301,
              statusDescription: "Moved Permanently",
              headers: {
                location: { value: redirectTo }
              }
            };
          }

          return request;
        }